version: 2.1
orbs:
  python: circleci/python@2
jobs:
  server-test:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo apt-get update && sudo apt-get install -y build-essential python3-dev python3-venv libgl1 libglib2.0-0
      - run:
          name: Run start_fastapi_server.sh and test
          command: /bin/bash scripts/start_fastapi_server.sh
      - store_test_results:
          path: junit.xml

workflows:
  build-and-test:
    jobs:
      - server-test